# Generated by Django 3.2 on 2021-04-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='znacka_typ_auta',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='ridicak',
            field=models.CharField(max_length=30),
        ),
    ]
