# Generated by Django 3.2 on 2021-04-24 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_auto_20210424_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='vypujceni_auta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.vypujcka'),
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='vypujcka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.vypujcka'),
        ),
    ]
